CC     = gcc
TARGET = big-mul
SRC    = big-mul.c

CFLAGS_DEBUG   = -Wall -gdwarf-5 -std=c99 -O0
CFLAGS_RELEASE = -Wall -std=c99 -O1

all: debug

debug: $(SRC)
	$(CC) $(CFLAGS_DEBUG) -o $(TARGET) $(SRC)

release: $(SRC)
	$(CC) $(CFLAGS_RELEASE) -o $(TARGET) $(SRC)

clean:
	rm -f $(TARGET)
